In [7]:
import polars as pl
df = pl.read_csv("data/SDG_COUNTRY.csv")
df.head()

shape: (5, 2)
┌────────────┬─────────────────┐
│ COUNTRY_ID ┆ COUNTRY_NAME_EN │
│ ---        ┆ ---             │
│ str        ┆ str             │
╞════════════╪═════════════════╡
│ AFG        ┆ Afghanistan     │
│ ALB        ┆ Albania         │
│ DZA        ┆ Algeria         │
│ ASM        ┆ American Samoa  │
│ AND        ┆ Andorra         │
└────────────┴─────────────────┘

In [8]:
print(df.shape)

(241, 2)

In [9]:

df.describe()

shape: (9, 3)
┌────────────┬────────────┬─────────────────┐
│ statistic  ┆ COUNTRY_ID ┆ COUNTRY_NAME_EN │
│ ---        ┆ ---        ┆ ---             │
│ str        ┆ str        ┆ str             │
╞════════════╪════════════╪═════════════════╡
│ count      ┆ 241        ┆ 241             │
│ null_count ┆ 0          ┆ 0               │
│ mean       ┆ null       ┆ null            │
│ std        ┆ null       ┆ null            │
│ min        ┆ ABW        ┆ Afghanistan     │
│ 25%        ┆ null       ┆ null            │
│ 50%        ┆ null       ┆ null            │
│ 75%        ┆ null       ┆ null            │
│ max        ┆ ZZA        ┆ Åland Islands   │
└────────────┴────────────┴─────────────────┘

In [10]:

df.null_count()

shape: (1, 2)
┌────────────┬─────────────────┐
│ COUNTRY_ID ┆ COUNTRY_NAME_EN │
│ ---        ┆ ---             │
│ u32        ┆ u32             │
╞════════════╪═════════════════╡
│ 0          ┆ 0               │
└────────────┴─────────────────┘

In [11]:

print(df.columns)

['COUNTRY_ID', 'COUNTRY_NAME_EN']